### ISSUE TITLE
python3-joblib compile error

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#3139]
**Describe the bug**
Looks like setuptools is too old in zeus

**Used configuration**
- zeus latest

**Additional**

> | ERROR: Do not try to fetch `setuptools>=42' for building. Please add its native recipe to DEPENDS.
> | Traceback (most recent call last):
> |   File "setup.py", line 22, in <module>
> |     setup(use_scm_version=True, extras_require=extras_require)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
> |     _install_setup_requires(attrs)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
> |     dist.fetch_build_eggs(dist.setup_requires)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
> |     replace_conflicting=True,
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
> |     raise DistributionNotFound(req, requirers)
> | pkg_resources.DistributionNotFound: The 'setuptools>=42' distribution was not found and is required by the application
> | WARNING: exit code 1 from a shell command.
> | 
> NOTE: recipe python3-tqdm-native-4.54.0-r0: task do_configure: Failed
> ERROR: Task (/opt/build/meta-sca/recipes-python/python-tqdm-native/python3-tqdm-native_4.54.0.bb:do_configure) failed with exit code '1'
> NOTE: Running task 1348 of 3926 (/opt/build/meta-sca/recipes-python/python-joblib-native/python3-joblib-native_0.17.0.bb:do_fetch)

**Comment by priv-kweihmann** [comment]
Fixed by downgrading to a compatible setuptools version
