### ISSUE TITLE
python3-tqdm-native requires newer setuptools on zeus

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#3152]
**Describe the bug**
python3-tqdm-native requires newer setuptools on zeus

**Used layer**
- zeus latest

**Additional**

>  ERROR: Execution of '/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/temp/run.do_configure.13774' failed with exit code 1:
> | ERROR: Do not try to fetch `setuptools>=42' for building. Please add its native recipe to DEPENDS.
> | Traceback (most recent call last):
> |   File "setup.py", line 22, in <module>
> |     setup(use_scm_version=True, extras_require=extras_require)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
> |     _install_setup_requires(attrs)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
> |     dist.fetch_build_eggs(dist.setup_requires)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
> |     replace_conflicting=True,
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-tqdm-native/4.54.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
> |     raise DistributionNotFound(req, requirers)
> | pkg_resources.DistributionNotFound: The 'setuptools>=42' distribution was not found and is required by the application

**Comment by priv-kweihmann** [comment]
Fixed in zeus
