### ISSUE TITLE
scancode doesn't return a value

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#3328]
**Describe the bug**
Looks like some dependency is missing or similar

**Additional**
>> bad-package:Traceback (most recent call last):
>> bad-package:  File "/opt/build/build/tmp/work/core2-64-scatest-linux/bad-package/1.0-r0/recipe-sysroot-native/usr/bin/licensecheck", line 190, in <module>
>> bad-package:    _raw_license = version_from_scancode(_args)
>> bad-package:  File "/opt/build/build/tmp/work/core2-64-scatest-linux/bad-package/1.0-r0/recipe-sysroot-native/usr/bin/licensecheck", line 107, in version_from_scancode
>> bad-package:    with open(args.result) as i:
>> bad-package:FileNotFoundError: [Errno 2] No such file or directory: '/opt/build/build/tmp/work/core2-64-scatest-linux/bad-package/1.0-r0/temp/sca_raw_scancode_raw.json'

**Comment by priv-kweihmann** [comment]
The thing that causes it is `PermissionError: [Errno 13] Permission denied: '/github/home/.cache'`
