### ISSUE TITLE
[zeus] libyajl2: does not compile

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#3397]
**Describe the bug**
On zeus native ruby extensions are not buildable - maybe it's best to disable the support, as zeus is more or less already near it EOL

**Additional**
> | current directory: /opt/build/build/tmp/work/core2-64-scatest-linux/ruby-libyajl2/2.0.0-r0/image/usr/lib/ruby/gems/gems/libyajl2-2.0.0/ext/libyajl2
> | /opt/build/build/tmp/work/core2-64-scatest-linux/ruby-libyajl2/2.0.0-r0/recipe-sysroot-native/usr/bin/ruby -r ./siteconf20201223-2620-yvjnoe.rb extconf.rb
> | creating Makefile
> | /opt/build/build/tmp/work/core2-64-scatest-linux/ruby-libyajl2/2.0.0-r0/image/usr/lib/ruby/gems/gems/libyajl2-2.0.0/ext/libyajl2
> | extconf.rb:105:in `makemakefiles': unhandled exception
> | 	from extconf.rb:139:in `<main>'
> | ERROR:  Error installing /opt/build/build/tmp/work/core2-64-scatest-linux/ruby-libyajl2/2.0.0-r0/libyajl2-2.0.0/libyajl2-2.0.0.gem:
> | 	ERROR: Failed to build gem native extension.
> | 
> |     Building has failed. See above output for more information on the failure.

**Comment by priv-kweihmann** [comment]
Fix in zeus, by disabling inspec support
