### ISSUE TITLE
scancode doesn't work in zeus

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#3515]
**Describe the bug**
Hard to say what the reason is, as log isn't complete here

**Additional**

> 2021-01-03T09:11:38.7053902Z NOTE: Running task 3437 of 3961 (/opt/build/sources/meta-sca/dynamic-distro/scatest/code-from-elsewhere/simple-c.bb:do_sca_slick_core)
> 2021-01-03T09:11:38.9010654Z NOTE: simple-c-1.0-r0 do_sca_scancode: Traceback (most recent call last):
> 2021-01-03T09:11:38.9011897Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/bin/scancode", line 11, in <module>
> 2021-01-03T09:11:38.9013037Z     load_entry_point('scancode-toolkit==3.2.3', 'console_scripts', 'scancode')()
> 2021-01-03T09:11:38.9014413Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
> 2021-01-03T09:11:38.9015487Z     return get_distribution(dist).load_entry_point(group, name)
> 2021-01-03T09:11:38.9016814Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
> 2021-01-03T09:11:38.9017755Z     return ep.load()
> 2021-01-03T09:11:38.9018919Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
> 2021-01-03T09:11:38.9019893Z     return self.resolve()
> 2021-01-03T09:11:38.9020733Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/sit
> 2021-01-03T09:11:38.9021645Z NOTE: recipe simple-c-1.0-r0: task do_sca_scancode: Succeeded

**Comment by priv-kweihmann** [comment]
> 2021-01-03T22:02:37.7962527Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/bad-package/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/commoncode/__init__.py", line 30
> 2021-01-03T22:02:37.7963933Z     def set_re_max_cache(max_cache=120.10.200):

this looks like an unwanted side effect of enforcing a proper PV in the recipes :facepalm:

**Comment by priv-kweihmann** [comment]
Fixed in zeus
