### ISSUE TITLE
scancode: needs licensecheck?

### ISSUE THREAD

**Issue by RobertBerger** [priv-kweihmann/meta-sca#3582]
**Am I doing something wrong?**

```
SCA_AVAILABLE_MODULES_append = " scancode"

SCA_ENABLED_MODULES_RECIPE += "\
                             scancode \
                             "

SCA_ENABLED_MODULES_IMAGE += "\
                             scancode \
                             "
```

```
bitbake core-image-minimal
```

**sca outputs this**

```
cat sca/scancode/raw/eudev-3.2.9.txt 

libudev:Traceback (most recent call last):
libudev:  File "/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/recipe-sysroot-native/usr/bin/licensecheck", line 199, in <module>
libudev:    _raw_license = version_from_scancode(_args)
libudev:  File "/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/recipe-sysroot-native/usr/bin/licensecheck", line 112, in version_from_scancode
libudev:    with open(args.result) as i:
libudev:FileNotFoundError: [Errno 2] No such file or directory: '/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/temp/sca_raw_scancode_raw.json'


eudev-dev:Traceback (most recent call last):
eudev-dev:  File "/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/recipe-sysroot-native/usr/bin/licensecheck", line 199, in <module>
eudev-dev:    _raw_license = version_from_scancode(_args)
eudev-dev:  File "/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/recipe-sysroot-native/usr/bin/licensecheck", line 112, in version_from_scancode
eudev-dev:    with open(args.result) as i:
eudev-dev:FileNotFoundError: [Errno 2] No such file or directory: '/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/temp/sca_raw_scancode_raw.json'


eudev:Traceback (most recent call last):
eudev:  File "/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/recipe-sysroot-native/usr/bin/licensecheck", line 199, in <module>
eudev:    _raw_license = version_from_scancode(_args)
eudev:  File "/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/recipe-sysroot-native/usr/bin/licensecheck", line 112, in version_from_scancode
eudev:    with open(args.result) as i:
eudev:FileNotFoundError: [Errno 2] No such file or directory: '/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master/tmp/work/armv7at2hf-vfp-resy-linux-gnueabi/eudev/3.2.9-r0/temp/sca_raw_scancode_raw.json'

```

**Comment by priv-kweihmann** [comment]
No no there is an internal helper tool of that name (taken from licensehelper-native) of that name. That maybe is confusing, but scancode and licensecheck module do work independantly

**Comment by priv-kweihmann** [comment]
Can't reproduce, can you please check if `licensecheck-helper-native` is part of DEPENDS

**Comment by RobertBerger** [comment]
I think I know what's going on. It's not for images, only for recipes, as you already documented it.

```
$ bitbake core-image-minimal -e | grep ^DEPENDS=
DEPENDS="  syslinux-native bmap-tools-native cdrtools-native btrfs-tools-native squashfs-tools-native e2fsprogs-native   qemuwrapper-cross depmodwrapper-cross cross-localedef-native python3-python-magic-native"
```
```
$ bitbake busybox -e | grep ^DEPENDS=
DEPENDS="virtual/arm-resy-linux-gnueabi-gcc virtual/arm-resy-linux-gnueabi-compilerlibs virtual/libc  kern-tools-native virtual/crypt python3-python-magic-native tracefiles-native             licensecheck-helper-native             python3-scancode-native             sca-recipe-scancode-rules-native             update-rc.d initscripts virtual/update-alternatives"
pokyuser@bbe52884db65:/workdir/build/imx6q-phytec-mira-rdk-nand-wic-master$ 
```

**Comment by priv-kweihmann** [comment]
Yes, indeed, guess the same applies to #3568 too, right?
Maybe appending to `SCA_ENABLED_MODULES_RECIPE` isn't a very good idea.

**Comment by RobertBerger** [comment]
appending `SCA_ENABLED_MODULES_IMAGE` is not a good idea.

#3568 should work with IMAGES and MODULES.

**Comment by priv-kweihmann** [comment]
Yes, you're right - can we consider this issue here closed?
