### ISSUE TITLE
Update to ruby-cross 3.0 required in master

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#4036]
**Describe the bug**
Current master breaks at ruby-cross, as upstream moved to 3.0.0 so cross and native compiler don't match anymore

**Additional**

> | /opt/build/build/tmp/work/x86_64-linux/ruby-cross-x86_64/2.7.2-r0/recipe-sysroot-native/usr/lib/ruby/3.0.0/x86_64-linux-gnu/rbconfig.rb:13:in `<module:RbConfig>': ruby lib version (3.0.0) doesn't match executable version (2.7.2) (RuntimeError)
> | 	from /opt/build/build/tmp/work/x86_64-linux/ruby-cross-x86_64/2.7.2-r0/recipe-sysroot-native/usr/lib/ruby/3.0.0/x86_64-linux-gnu/rbconfig.rb:11:in `<top (required)>'
> | 	from /opt/build/build/tmp/work/x86_64-linux/ruby-cross-x86_64/2.7.2-r0/recipe-sysroot-native/usr/lib/ruby/3.0.0/fileutils.rb:4:in `require'
> | 	from /opt/build/build/tmp/work/x86_64-linux/ruby-cross-x86_64/2.7.2-r0/recipe-sysroot-native/usr/lib/ruby/3.0.0/fileutils.rb:4:in `<top (required)>'
> | 	from ../ruby-2.7.2/tool/transform_mjit_header.rb:5:in `require'
> | 	from ../ruby-2.7.2/tool/transform_mjit_header.rb:5:in `<main>'
> | uncommon.mk:241: recipe for target '.ext/include/x86_64-linux-gnu/rb_mjit_min_header-2.7.2.h' failed
> | make: *** [.ext/include/x86_64-linux-gnu/rb_mjit_min_header-2.7.2.h] Error 1
> | make: *** Waiting for unfinished jobs....
> | ../ruby-2.7.2/tool/ifchange "--timestamp=.rbconfig.time" rbconfig.rb rbconfig.tmp
> | rbconfig.rb updated

**Comment by priv-kweihmann** [comment]
Will be handled by #3444
