### ISSUE TITLE
python3-setuptools-rust-native breaks zeus and dunfell

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#4064]
**Describe the bug**
`python3-setuptools-rust-native` doesn't work on dunfell and zeus

**Additional**

> | Traceback (most recent call last):
> |   File "setup.py", line 7, in <module>
> |     python_requires='>=3.5'
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-rust-native/0.11.6-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
> |     _install_setup_requires(attrs)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-rust-native/0.11.6-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
> |     dist.fetch_build_eggs(dist.setup_requires)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-rust-native/0.11.6-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
> |     replace_conflicting=True,
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-rust-native/0.11.6-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
> |     raise DistributionNotFound(req, requirers)
> | pkg_resources.DistributionNotFound: The 'setuptools>=46.1' distribution was not found and is required by the application
> | WARNING: exit code 1 from a shell command.

**Comment by priv-kweihmann** [comment]
Fixed in dunfell and zeus
