### ISSUE TITLE
python3-setuptools-scm-native fails to install on zeus

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#4632]
**Describe the bug**
python3-setuptools-scm-native fails to install on zeus

**Additional**

> <pkg_resources.WorkingSet object at 0x7fa3ecdeb210>
> Traceback (most recent call last):
>   File "setup.py", line 52, in <module>
>     setuptools.setup(**scm_config())
>   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
>     return distutils.core.setup(**attrs)
>   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/distutils/core.py", line 108, in setup
>     _setup_distribution = dist = klass(attrs)
>   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/dist.py", line 446, in __init__
>     k: v for k, v in attrs.items()
>   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/distutils/dist.py", line 292, in __init__
>     self.finalize_options()
>   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/setuptools/dist.py", line 733, in finalize_options
>     ep.require(installer=self.fetch_build_egg)
>   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2465, in require
>     items = working_set.resolve(reqs, env, installer, extras=self.extras)
>   File "/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.VersionConflict: (setuptools 41.2.0 (/opt/build/build/tmp/work/x86_64-linux/python3-setuptools-scm-native/6.0.1-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages), Requirement.parse('setuptools>=45'))
> WARNING: exit code 1 from a shell command.

**Comment by priv-kweihmann** [comment]
Fixed in zeus by reverting
