### ISSUE TITLE
[BUG][rocko] `python3-pytest-native-5.3.2-r0 do_compile` fails

### ISSUE THREAD

**Issue by agrexgh** [priv-kweihmann/meta-sca#4884]
Hello.
I'd like to use `meta-sca` for my project.

I use yocto `2.4.2` , so I think the branch `vrocko_1.21.0` of `meta-sca` would fit with my project,
but bitbake returns some error.
There're **2 problems** at `bitbake` ( see Problem 1, Problem 2).
I thought `vrocko` of `meta-sca` supports `rocko` of `yocto`, is this my misunderstanding?

#### 1.Making recipe

This is a copy of `meta-skeleton/recipes-kernel/hello-mod/hello-mod_0.1.bb` in `git clone https://git.yoctoproject.org/git/poky`.
`Makefile` and `hello.c` and `COPYING` are also copied in `files` directory.

```
SUMMARY = "Example of how to build an external Linux kernel module"
LICENSE = "GPLv2"
LIC_FILES_CHKSUM = "file://COPYING;md5=12f884d2ae1ff87c09e5b7ccc2c4ca7e"

inherit module sca

SRC_URI = "file://Makefile \
           file://hello.c \
           file://COPYING \
          "

S = "${WORKDIR}"
```

#### 2.Adding layer

add line below to `build/conf/bblayers.conf`.
```
BBLAYERS ?= " \
  ...
  /work/poky/meta-sca \ #added line
  "
```

#### 3.Running container

I executed below according to [here](https://github.com/priv-kweihmann/meta-sca#use-of-containers)

```
$ docker pull privkweihmann/yocto-sca-minimal:latest
$ docker run --name meta-sca-test \
	-u "$(id -u $USER):$(id -g $USER)" \
	-it \
	--mount type=bind,src="$PWD",dst="$PWD" \
	-w $(pwd) \
	--mount type=bind,src=/etc/passwd,dst=/etc/passwd,readonly \
	--mount type=bind,src=/etc/group,dst=/etc/group,readonly \
	--mount type=bind,src=/etc/shadow,dst=/etc/shadow,readonly \
	--mount type=bind,src=/work/wgetrc,dst=/etc/wgetrc,readonly \
	--privileged \
	privkweihmann/yocto-sca-minimal
```

#### 4.Executing command

```
$ . oe-init-build-env #Once this is executed, this is needless for every bitbake.
$ bitbake test-cpplint
```

### ~~Problem 1: `cppcheck-native-1.90-r0 do_fetch` fails.~~ <- issued as #4903

`cppcheck-native-1.90-r0 do_fetch` fails.
Error log is below.

```
WARNING: cppcheck-native-1.90-r0 do_fetch: Failed to fetch URL git://github.com/danmar/cppcheck.git;protocol=https;tag=1.90, attempting MIRRORS if available
ERROR: cppcheck-native-1.90-r0 do_fetch: Fetcher failure: Unable to find revision 077e652de43ad962be0454d7be347816f7482739 in branch master even from upstream
ERROR: cppcheck-native-1.90-r0 do_fetch: Fetcher failure for URL: 'git://github.com/danmar/cppcheck.git;protocol=https;tag=1.90'. Unable to fetch URL from any source.
ERROR: cppcheck-native-1.90-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /work/poky/build/tmp/work/x86_64-linux/cppcheck-native/1.90-r0/temp/log.do_fetch.20227
ERROR: Task (/work/poky/meta-sca/recipes-sca/cppcheck-native/cppcheck-native_1.90.bb:do_fetch) failed with exit code '1'
```

#### How to fix this: Edit `git.py` before executing `bitbake`

To fix problem 1, edit line 175 as below.
(When you get same errors in another recipe, restore the git.py to original one)

```
branches = ud.parm.get("branch", "main").split(',') # master -> main
```

### Problem 2: `python3-pytest-native-5.3.2-r0 do_compile` fails

After fixing Problem1, `python3-pytest-native-5.3.2-r0 do_compile` fails.
I couldn't find how to fix...
Error log is below.

```
ERROR: python3-pytest-native-5.3.2-r0 do_compile: python3 setup.py build_ext execution failed.
ERROR: python3-pytest-native-5.3.2-r0 do_compile: Function failed: do_compile (log file is located at /work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/temp/log.do_compile.13764)
ERROR: Logfile of failure stored in: /work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/temp/log.do_compile.13764
Log data follows:
| DEBUG: Executing shell function do_compile
| Traceback (most recent call last):
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/core.py", line 148, in setup
|     dist.run_commands()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
|     self.run_command(cmd)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
|     cmd_obj.run()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 152, in run
|     self.run_command("egg_info")
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
|     self.distribution.run_command(command)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
|     cmd_obj.run()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 280, in run
|     self.find_sources()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 295, in find_sources
|     mm.run()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 526, in run
|     self.add_defaults()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 562, in add_defaults
|     sdist.add_defaults(self)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/py36compat.py", line 34, in add_defaults
|     self._add_defaults_python()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/sdist.py", line 134, in _add_defaults_python
|     self.filelist.extend(build_py.get_source_files())
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/command/build_py.py", line 301, in get_source_files
|     return [module[-1] for module in self.find_all_modules()]
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/command/build_py.py", line 296, in find_all_modules
|     m = self.find_package_modules(package, package_dir)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/command/build_py.py", line 218, in find_package_modules
|     self.check_package(package, package_dir)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/build_py.py", line 163, in check_package
|     init_py = orig.build_py.check_package(self, package, package_dir)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/command/build_py.py", line 191, in check_package
|     "package directory '%s' does not exist" % package_dir)
| distutils.errors.DistutilsFileError: package directory 'find_namespace:' does not exist
|
| During handling of the above exception, another exception occurred:
|
| Traceback (most recent call last):
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
|     yield saved
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
|     yield
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
|     _execfile(setup_script, ns)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
|     exec(code, globals, locals)
|   File "/tmp/easy_install-cpdo6g5_/setuptools-54.2.0/setup.py", line 162, in <module>
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/core.py", line 163, in setup
|     raise SystemExit("error: " + str(msg))
| SystemExit: error: package directory 'find_namespace:' does not exist
|
| During handling of the above exception, another exception occurred:
|
| Traceback (most recent call last):
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1104, in run_setup
|     run_setup(setup_script, args)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 257, in run_setup
|     raise
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/contextlib.py", line 77, in __exit__
|     self.gen.throw(type, value, traceback)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
|     yield
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/contextlib.py", line 77, in __exit__
|     self.gen.throw(type, value, traceback)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 170, in save_modules
|     saved_exc.resume()
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 145, in resume
|     six.reraise(type, exc, self._tb)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
|     raise value.with_traceback(tb)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 158, in save_modules
|     yield saved
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 199, in setup_context
|     yield
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 254, in run_setup
|     _execfile(setup_script, ns)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 49, in _execfile
|     exec(code, globals, locals)
|   File "/tmp/easy_install-cpdo6g5_/setuptools-54.2.0/setup.py", line 162, in <module>
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/core.py", line 163, in setup
|     raise SystemExit("error: " + str(msg))
| SystemExit: error: package directory 'find_namespace:' does not exist
|
| During handling of the above exception, another exception occurred:
|
| Traceback (most recent call last):
|   File "setup.py", line 39, in <module>
|     main()
|   File "setup.py", line 34, in main
|     install_requires=INSTALL_REQUIRES,
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/distutils/core.py", line 108, in setup
|     _setup_distribution = dist = klass(attrs)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/dist.py", line 325, in __init__
|     self.fetch_build_eggs(attrs['setup_requires'])
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/dist.py", line 446, in fetch_build_eggs
|     replace_conflicting=True,
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 855, in resolve
|     dist = best[req.key] = env.best_match(req, ws, installer)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1127, in best_match
|     return self.obtain(req, installer)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1139, in obtain
|     return installer(requirement)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/dist.py", line 518, in fetch_build_egg
|     return cmd.easy_install(req)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 672, in easy_install
|     return self.install_item(spec, dist.location, tmpdir, deps)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 698, in install_item
|     dists = self.install_eggs(spec, download, tmpdir)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 879, in install_eggs
|     return self.build_and_install(setup_script, setup_base)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
|     self.run_setup(setup_script, setup_base, args)
|   File "/work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1106, in run_setup
|     raise DistutilsError("Setup script exited with %s" % (v.args[0],))
| distutils.errors.DistutilsError: Setup script exited with error: package directory 'find_namespace:' does not exist
| ERROR: python3 setup.py build_ext execution failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /work/poky/build/tmp/work/x86_64-linux/python3-pytest-native/5.3.2-r0/temp/log.do_compile.13764)
ERROR: Task (/work/poky/meta-sca/recipes-python/python-pytest-native/python3-pytest-native_5.3.2.bb:do_compile) failed with exit code '1'
```

**Comment by priv-kweihmann** [comment]
Yes, it does support rocko but is not actively supported in a long time.
Regarding issue 1:
- yes that is a known one, cppcheck switched their branch naming after rocko branch was declared EOL, but you're welcome to provide patches.

Regarding issue 2:
- I would suggest to use `privkweihmann/yocto-sca-minimal:krogoth` instead of `privkweihmann/yocto-sca-minimal:latest`, as I'm pretty sure that this will somehow invoke the host side python. Furthermore it is possible that it will require a more recent version of python3-setuptools from poky or whatever layer that could provide.
Here as well I have to say, rocko branch hasn't been tested in ages

**Comment by agrexgh** [comment]
Thank you for replying me!
I'll try `krogoth` version container.

> yes that is a known one, cppcheck switched their branch naming after rocko branch was declared EOL, but you're welcome to provide patches.
I think this is caused yocto's soruce.
How can I apply patches?

**Comment by agrexgh** [comment]
@priv-kweihmann 

> Problem 1: cppcheck-native-1.90-r0 do_fetch fails.

This seems to be solved without patching yocto's source.
Only adding `branch=main` to `SRC_URI` in `cppcheck-native_1.90.bb` would solve this.
Could you try it?

**Comment by priv-kweihmann** [comment]
I guess that assumption is correct (I'm unfortunately not able to test it any time soon).

What you can do is to create cppcheck-native_1.90.bbappend in your layer with the following content
```
SRC_URI = "git://github.com/danmar/cppcheck.git;protocol=https;nobranch=1 \
           file://0001-Makefile-fixes.patch \
           file://cppcheck.sca.description"
SRCREV = "077e652de43ad962be0454d7be347816f7482739"
```
the used SRCREV is the one of the 1.90 tag (and it's way safer to use revisions instead of tags - something that was done for thud+ branches)

**Comment by agrexgh** [comment]
@priv-kweihmann 
Thank you for advising me!
I confirmed both my `branch=main` method and your `nobranch=1` method worked.
And I think `nobranch=1` method is more generic (for like a situation that the repository have neither `master` or `main`).

Problem 1 is separated as #4903, so I'd like to use this issue to follow Problem 2.

**Comment by agrexgh** [comment]
fFxed this title and description to focus on Problem 2.

**Comment by priv-kweihmann** [comment]
your PR got merged - I will look into the  2nd issue the other day

**Comment by agrexgh** [comment]
I've been also investigating 2nd issue now.
It may be caused by old `python3-setuptools` setuptools (rocko ver in meta-sca is 36.2.7).
I tried to update to 50.3.2, but error changed to another one.
I wondered it's because python3 installed in `krogoth` image is old(3.4.3), so upgrade python3(in addition ,git ,texinfo was needed for bitbake, so upgraded them also).
After that I got error like below, I'm stuck for this.

```Shell
ERROR: python3-setuptools-native-50.3.2-r0 do_compile: python3 setup.py build_ext execution failed.
ERROR: python3-setuptools-native-50.3.2-r0 do_compile: Function failed: do_compile (log file is located at /work/poky/build/tmp/work/x86_64-linux/python3-setuptools-native/50.3.2-r0/temp/log.do_compile.15226)
ERROR: Logfile of failure stored in: /work/poky/build/tmp/work/x86_64-linux/python3-setuptools-native/50.3.2-r0/temp/log.do_compile.15226
Log data follows:
| DEBUG: Executing shell function do_compile
| Traceback (most recent call last):
|   File "setup.py", line 195, in <module>
|     require_metadata()
|   File "setup.py", line 24, in require_metadata
|     raise RuntimeError(msg)
| RuntimeError: Cannot build setuptools without metadata. Run `bootstrap.py`.
| ERROR: python3 setup.py build_ext execution failed.
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /work/poky/build/tmp/work/x86_64-linux/python3-setuptools-native/50.3.2-r0/temp/log.do_compile.15226)
ERROR: Task (virtual:native:/work/poky/meta-sca/recipes-python/python-setuptools/python3-setuptools_50.3.2.bb:do_compile) failed with exit code '1'
```

**Comment by agrexgh** [comment]
> ```shell
> ERROR: python3-setuptools-native-50.3.2-r0 do_compile: python3 setup.py build_ext execution failed.
> ERROR: python3-setuptools-native-50.3.2-r0 do_compile: Function failed: do_compile (log file is located at /work/poky/build/tmp/work/x86_64-linux/python3-setuptools-native/50.3.2-r0/temp/log.do_compile.15226)
> ERROR: Logfile of failure stored in: /work/poky/build/tmp/work/x86_64-linux/python3-setuptools-native/50.3.2-r0/temp/log.do_compile.15226
> Log data follows:
> | DEBUG: Executing shell function do_compile
> | Traceback (most recent call last):
> |   File "setup.py", line 195, in <module>
> |     require_metadata()
> |   File "setup.py", line 24, in require_metadata
> |     raise RuntimeError(msg)
> | RuntimeError: Cannot build setuptools without metadata. Run `bootstrap.py`.
> | ERROR: python3 setup.py build_ext execution failed.
> | WARNING: exit code 1 from a shell command.
> | ERROR: Function failed: do_compile (log file is located at /work/poky/build/tmp/work/x86_64-linux/python3-setuptools-native/50.3.2-r0/temp/log.do_compile.15226)
> ERROR: Task (virtual:native:/work/poky/meta-sca/recipes-python/python-setuptools/python3-setuptools_50.3.2.bb:do_compile) failed with exit code '1'
> ```

I wonder if pypa/setuptools#1527 is related for above.

**Comment by agrexgh** [comment]
To fix pypa/setuptools#1527, setuptools should be updated to upper than 52.0.0, but this ver isn't compatible for python-native 5.3.2.
Is this problem of original rocko of yocto?
@priv-kweihmann

**Comment by priv-kweihmann** [comment]
upgrading python and setuptools always has been tricky - I would suggest to downgrade the pytest to 3.x (which is the last version supporting setuptool < 40.0) - meta-openembedded does provide you with such a recipe (http://cgit.openembedded.org/meta-openembedded/tree/meta-python/recipes-devtools/python/python3-pytest_3.2.2.bb?h=rocko) - just use `PREFERRED_VERSION-python3-pytest-native = "3.2.2"` in your local.conf and it should work.
If meta-openembedded is already part of your layer stack, maybe a `BBMASK` of the meta-sca recipe does the trick as well

BTW I would highly encourage you to switch to a more recent branch than rocko (which is EOL for >2.5yrs)

**Comment by agrexgh** [comment]
>  just use PREFERRED_VERSION-python3-pytest-native = "3.2.2"
It works!! Thank you!
But now util-linux compile error appears...

> BTW I would highly encourage you to switch to a more recent branch than rocko (which is EOL for >2.5yrs)
That's too bad. I've been use this for about 3 years...
I'll advise my boss, thank you for your recommendation.

Do you think you stop `meta-sca` supporting rocko?
@priv-kweihmann

**Comment by agrexgh** [comment]
> just use PREFERRED_VERSION-python3-pytest-native = "3.2.2" in your local.conf and it should work.

I cloned `meta-openembedded`,
and add below to `bblayers.conf`

```
  /work/poky/meta-openembedded/meta-oe \
  /work/poky/meta-openembedded/meta-python \
```
and add `PREFERRED_VERSION_python3-pytest-native = "3.2.2"`(character after VERSION is underline ;) ),
it works.
Thank you for advise!

But now, I have util-linux do_compile error...
The error says

```
../util-linux-2.30/lib/randutils.c:41:18: error: ‘__NR_getrandom’ undeclared (first use in this function)
```

---

> BTW I would highly encourage you to switch to a more recent branch than rocko (which is EOL for >2.5yrs)

That's too bad, I've been using rocko for more than 3 years..
I'll advise my boss to use recent version of yocto.
Thank you for this advise too!

Do you think you stop `meta-sca`'s supporting `rocko` ?

**Comment by priv-kweihmann** [comment]
The last change that wasn't about documents or CI was this here https://github.com/priv-kweihmann/meta-sca/commit/4a5c94c7ccd01b1fbb2c76185455fd3a1295dd05 (dating 2020/02/02) - so yeah, support has officially end a long time ago.

**Comment by agrexgh** [comment]
> it does support rocko

I misunderstood this sentence as "Supporting it now".

> The last change that wasn't about documents or CI was this here 4a5c94c (dating 2020/02/02) - so yeah, support has officially ended a long time ago.

I see https://github.com/priv-kweihmann/meta-sca/blob/master/SECURITY.md and I noticed rocko is not included supported branch,
I'm sorry for ignorance.
My problem isn't solved perfectly, but first, rocko is not supported so I'll close this issue.

Big appretiation for your kind help.
