### ISSUE TITLE
[zeus] extractcode produces invalid version

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#5000]
**Describe the bug**
seen on zeus

**Additional**

> 2021-04-10T09:23:58.1632677Z NOTE: simple-c-1.0-r0 do_sca_scancode: Traceback (most recent call last):
> 2021-04-10T09:23:58.1634518Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
> 2021-04-10T09:23:58.1635755Z     ws.require(__requires__)
> 2021-04-10T09:23:58.1637296Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
> 2021-04-10T09:23:58.1638755Z     needed = self.resolve(parse_requirements(requirements))
> 2021-04-10T09:23:58.1640452Z   File "/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
> 2021-04-10T09:23:58.1641861Z     raise VersionConflict(dist, req).with_context(dependent_req)
> 2021-04-10T09:23:58.1644315Z pkg_resources.ContextualVersionConflict: (extractcode 0.0.0 (/opt/build/build/tmp/work/core2-64-scatest-linux/simple-c/1.0-r0/recipe-sysroot-native/usr/lib/python3.7/site-packages), Requirement.parse('extractcode[full]>=21.2.24'), {'scancode-toolkit'})

**Comment by priv-kweihmann** [comment]
Fixed in zeus
