### ISSUE TITLE
pylint is missing platformdirs

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#6849]
**Additional**
>> Traceback (most recent call last):
>>   File "/opt/build/build/tmp/work/x86_64-linux/python3-pylint-native/2.10.2-r0/recipe-sysroot-native/usr/bin/pylint", line 6, in <module>
>>     from pkg_resources import load_entry_point
>>   File "/opt/build/build/tmp/work/x86_64-linux/python3-pylint-native/2.10.2-r0/recipe-sysroot-native/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3254, in <module>
>>     def _initialize_master_working_set():
>>   File "/opt/build/build/tmp/work/x86_64-linux/python3-pylint-native/2.10.2-r0/recipe-sysroot-native/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
>>     f(*args, **kwargs)
>>   File "/opt/build/build/tmp/work/x86_64-linux/python3-pylint-native/2.10.2-r0/recipe-sysroot-native/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
>>     working_set = WorkingSet._build_master()
>>   File "/opt/build/build/tmp/work/x86_64-linux/python3-pylint-native/2.10.2-r0/recipe-sysroot-native/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 586, in _build_master
>>     return cls._build_from_requirements(__requires__)
>>   File "/opt/build/build/tmp/work/x86_64-linux/python3-pylint-native/2.10.2-r0/recipe-sysroot-native/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
>>     dists = ws.resolve(reqs, Environment())
>>   File "/opt/build/build/tmp/work/x86_64-linux/python3-pylint-native/2.10.2-r0/recipe-sysroot-native/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
>>     raise DistributionNotFound(req, requirers)
>> pkg_resources.DistributionNotFound: The 'platformdirs>=2.2.0' distribution was not found and is required by pylint

**Comment by priv-kweihmann** [comment]
> platformdirs 0.0.0
that seems to be the reason - likely depending on `setuptools-scm` will fix the issue
