### ISSUE TITLE
pyenchant doesn't build

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#740]
**Describe the bug**
pyenchant doesn't build in CI container

**Additional**

> ERROR: Logfile of failure stored in: /opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/temp/log.do_compile.46877
> Log data follows:
> | DEBUG: Executing shell function do_compile
> | Traceback (most recent call last):
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/pyenchant-2.0.0/setup.py", line 212, in <module>
> |     import enchant
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/pyenchant-2.0.0/enchant/__init__.py", line 92, in <module>
> |     from enchant import _enchant as _e
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/pyenchant-2.0.0/enchant/_enchant.py", line 145, in <module>
> |     raise ImportError(msg)
> | ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
> | ERROR: 'python3 setup.py build ' execution failed.
> | WARNING: exit code 1 from a shell command.
> | ERROR: Execution of '/opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/temp/run.do_compile.46877' failed with exit code 1:
> | Traceback (most recent call last):
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/pyenchant-2.0.0/setup.py", line 212, in <module>
> |     import enchant
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/pyenchant-2.0.0/enchant/__init__.py", line 92, in <module>
> |     from enchant import _enchant as _e
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-pyenchant-native/2.0.0-r0/pyenchant-2.0.0/enchant/_enchant.py", line 145, in <module>
> |     raise ImportError(msg)
> | ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
> | WARNING: exit code 1 from a shell command.

**Comment by priv-kweihmann** [comment]
This will be fixed with pyenchant 3.0 (which is still in the works) (see https://pyenchant.github.io/pyenchant/changelog.html#breaking-changes) - Let's just wait

**Comment by priv-kweihmann** [comment]
And currently it's just a master thing...
So I guess we could restore the original enchant from oe at least temporary
