### ISSUE TITLE
[thud] wheel isn't buildable

### ISSUE THREAD

**Issue by priv-kweihmann** [priv-kweihmann/meta-sca#791]
**Describe the bug**
The latest update of python3-wheel leads to an error

**Additional**

> Log data follows:
> | DEBUG: Executing shell function do_configure
> | ERROR: Do not try to fetch `setuptools>=40.9.0' for building. Please add its native recipe to DEPENDS.
> | Traceback (most recent call last):
> |   File "setup.py", line 4, in <module>
> |     setup(maintainer=u'Alex Grönholm')
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-wheel-native/0.34.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/__init__.py", line 130, in setup
> |     _install_setup_requires(attrs)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-wheel-native/0.34.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/__init__.py", line 125, in _install_setup_requires
> |     dist.fetch_build_eggs(dist.setup_requires)
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-wheel-native/0.34.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
> |     replace_conflicting=True,
> |   File "/opt/build/build/tmp/work/x86_64-linux/python3-wheel-native/0.34.2-r0/recipe-sysroot-native/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 777, in resolve
> |     raise DistributionNotFound(req, requirers)
> | pkg_resources.DistributionNotFound: The 'setuptools>=40.9.0' distribution was not found and is required by the application
> | WARNING: exit code 1 from a shell command.
> | ERROR: Function failed: do_configure (log file is located at /opt/build/build/tmp/work/x86_64-linux/python3-wheel-native/0.34.2-r0/temp/log.do_configure.104197)
> NOTE: recipe python3-wheel-native-0.34.2-r0: task do_configure: Failed

**Comment by priv-kweihmann** [comment]
Done by 52c8641
