### ISSUE TITLE
[honister][hardknott] python3-black-native fails do_compile since 'layer.conf: lower BBFILE_PRIORITY to 1'

### ISSUE THREAD

**Issue by kk6ho** [priv-kweihmann/meta-sca#8192]
**Describe the bug**
Since Nov 25 2021 Our honister and hardknott CI builds started failing due python3-black-native failing to build. Our Yocto master build does not have this error.

Using git bisect, I isolated to this commit (honister): 

git bisect bad
6bff9ba12b5b172ceae9c9596bf9bbd58a6d1e7f is the first bad commit
commit 6bff9ba12b5b172ceae9c9596bf9bbd58a6d1e7f
Author: Konrad Weihmann <kweihmann@outlook.com>
Date:   Sun Nov 21 18:29:51 2021 +0100

    layer.conf: lower BBFILE_PRIORITY to 1
    
    so in case there is an alternative the other recipe will win
    
    Relates to #8113
    
    Signed-off-by: Konrad Weihmann <kweihmann@outlook.com>

 conf/layer.conf | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

**Used layer**
- hash of meta-sca layer   honister: 9bc51ed,   hardknott: e3268377e
- poky hash   honister: b53230c08d , hardknott: f6ad205e1a

**Error log**
```
ERROR: python3-black-native-21.10b0-r0 do_compile: 'python3 setup.py build ' execution failed.
ERROR: python3-black-native-21.10b0-r0 do_compile: ExecutionError('/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/temp/run.do_compile.1264276', 1, None, None)
ERROR: Logfile of failure stored in: /home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/temp/log.do_compile.1264276
Log data follows:
| DEBUG: Executing shell function do_compile
| WARNING: The wheel package is not available.
| /home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/bin/python3-native/python3: No module named pip
| Traceback (most recent call last):
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
|     subprocess.check_call(cmd)
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/subprocess.py", line 373, in check_call
|     raise CalledProcessError(retcode, cmd)
| subprocess.CalledProcessError: Command '['/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/bin/python3-native/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpqvubqnoz', '--quiet', 'setuptools_scm[toml]>=6.3.1']' returned non-zero exit status 1.
| 
| The above exception was the direct cause of the following exception:
| 
| Traceback (most recent call last):
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/black-21.10b0/setup.py", line 48, in <module>
|     setup(
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
|     _install_setup_requires(attrs)
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
|     dist.fetch_build_eggs(dist.setup_requires)
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
|     resolved_dists = pkg_resources.working_set.resolve(
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
|     dist = best[req.key] = env.best_match(
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
|     return self.obtain(req, installer)
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
|     return installer(requirement)
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
|     return fetch_build_egg(self, req)
|   File "/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
|     raise DistutilsError(str(e)) from e
| distutils.errors.DistutilsError: Command '['/home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/recipe-sysroot-native/usr/bin/python3-native/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpqvubqnoz', '--quiet', 'setuptools_scm[toml]>=6.3.1']' returned non-zero exit status 1.
| ERROR: 'python3 setup.py build ' execution failed.
| WARNING: /home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/temp/run.do_compile.1264276:178 exit 1 from 'exit 1'
| WARNING: Backtrace (BB generated script):
|       #1: bbfatal_log, /home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/temp/run.do_compile.1264276, line 178
|       #2: distutils3_do_compile, /home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/temp/run.do_compile.1264276, line 168
|       #3: do_compile, /home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/temp/run.do_compile.1264276, line 157
|       #4: main, /home/geoff/yocto-honister/poky/build-gx/tmp/work/x86_64-linux/python3-black-native/21.10b0-r0/temp/run.do_compile.1264276, line 182
ERROR: Task (/home/geoff/yocto-honister/poky/build-gx/../meta-sca/recipes-python/python-black-native/python3-black-native_21.10b0.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 441 tasks of which 326 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/geoff/yocto-honister/poky/build-gx/../meta-sca/recipes-python/python-black-native/python3-black-native_21.10b0.bb:do_compile
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

```

**Comment by priv-kweihmann** [comment]
This is somehow true as upstream poky didn't do the updates needed, but it can be mitigated on a distro or local.conf level as done here https://github.com/priv-kweihmann/meta-sca/blob/e3268377e0a4c0d774d5e9a193f017682e018979/conf/variant/scatest-qemux86-64/local.conf.sample#L17.
I agree that might be worth documenting, but it's not a bug in my opinion

**Comment by kk6ho** [comment]
Thanks Konrad for the work-around tip.  I also found the related issue
https://github.com/priv-kweihmann/meta-sca/issues/8170

I had to pin also for my build :
`PREFERRED_VERSION:python3-cython-native = "0.29.24"`

However, I'm getting a different error now in the build due to clashing
file packaging with similar package names

python3-booleanpy-native in meta-python vs. python3-boolean.py-native in
meta-sca.

```ERROR: python3-reuse-native-0.13.0-r0 do_prepare_recipe_sysroot: The
file
/usr/lib/python3.9/site-packages/boolean.py-3.8-py3.9.egg-info/dependency_links.txt
is installed by both python3-booleanpy-native and
python3-boolean.py-native, aborting
ERROR: Logfile of failure stored in:
/home/geoff/yocto/poky/build-gxresection/tmp/work/x86_64-linux/python3-reuse-native/0.13.0-r0/temp/log.do_prepare_recipe
_sysroot.128117
ERROR: Task
(/home/geoff/yocto/poky/build-gxresection/../meta-sca/recipes-sca/python3-reuse-native/python3-reuse-native_0.13.0.bb:
do_prepare_recipe_sysroot)
failed with exit code '1'
```

**Comment by priv-kweihmann** [comment]
Could open up an additional issue for that please.
I think we have a naming issue here, which should be fixable fairly easily

**Comment by priv-kweihmann** [comment]
Just created one - will fix that later that day

**Comment by kk6ho** [comment]
Hi Konrad,

Thanks. That worked. I would have created another issue last night but
it was 1am and I needed to get some sleep before the Yocto Summit at
4am :-).
